import "@babel/polyfill"
import './fonts/fonts.sass'
import './components/general_css/general.sass'
import './components/general_css/variables.sass'
import './components/slide_up/slide_up.sass'
import './components/header/header.sass'
import './components/content/apartments/content.sass'
import './components/footer/footer.sass'
import './components/footer/form/form.sass'
import './components/media_queries/media_1600.sass'
import './components/media_queries/media_1024.sass'

import './components/slide_up/slide_up'
import './components/content/apartments/request'
import './components/content/apartments/ContentHandler'
import './components/content/apartments/ApartmentBox'
import './components/footer/form/form'